# Based on the latest HugoBlox Academic CV template.
title: Xuanli Lin
baseURL: 'https://xlin.io/'
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: ['\.ipynb$', '.ipynb_checkpoints$', '\.Rmd$', '\.Rmarkdown$', '_cache$']
permalinks:
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
build:
  buildStats:
    enable: true
caches:
  misc:
    dir: ':resourceDir/_gen/misc'
  getresource:
    dir: ':resourceDir/_gen/getresource'
imaging:
  _merge: none
  resampleFilter: lanczos
  jpeg:
    quality: 90
  webp:
    quality: 90
    hint: picture
  avif:
    quality: 90
    hint: picture
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
  exec:
    allow: ['^(dart-)?sass$', '^go$', '^git$', '^node$', '^postcss$', '^tailwindcss$']
sitemap:
  _merge: deep
